name: 'submodule update'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "mo/br3"
    events:
      - closed

jobs:
  test:
    name: sup
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'MOvenshire/base'
      CHECKOUT_BRANCH: 'main'
      PR_AGAINST_BRANCH: 'main'
      OWNER: 'MOvenshire'
    steps:
    - name: checkout parent
      uses: actions/checkout@v2
    - name: run action
      id: run_action
      uses: ./
      with:
        github_token: ${{ secrets.WORKFLOWS }}
        parent_repository: ${{ env.PARENT_REPOSITORY }}
        checkout_branch: ${{ env.CHECKOUT_BRANCH}}
        pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
        owner: ${{ env.OWNER }}